// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api_AppCrud.Models
{
    public partial class Comps
    {
        public int Idcomp { get; set; }
        public string Nombre { get; set; }
    }
}