// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Api_AppCrud.Models;

namespace Api_AppCrud.Data
{
    public partial class crudEmpleadoContext : DbContext
    {
        public crudEmpleadoContext()
        {
        }

        public crudEmpleadoContext(DbContextOptions<crudEmpleadoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Comps> Comps { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<VistaEmpleado> VistaEmpleado { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Comps>(entity =>
            {
                entity.HasKey(e => e.Idcomp);

                entity.ToTable("comps");

                entity.Property(e => e.Idcomp).HasColumnName("idcomp");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasColumnName("nombre");
            });

            modelBuilder.Entity<Empleado>(entity =>
            {
                entity.HasKey(e => e.IdEmp);

                entity.Property(e => e.IdEmp).HasColumnName("idEmp");

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasColumnName("apellido");

                entity.Property(e => e.Direccion)
                    .IsRequired()
                    .HasColumnName("direccion");

                entity.Property(e => e.Idcomp).HasColumnName("idcomp");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasColumnName("nombre");

                entity.Property(e => e.Telefono)
                    .IsRequired()
                    .HasColumnName("telefono");
            });

            modelBuilder.Entity<VistaEmpleado>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("VistaEmpleado");

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasColumnName("apellido");

                entity.Property(e => e.Compañia).IsRequired();

                entity.Property(e => e.Direccion)
                    .IsRequired()
                    .HasColumnName("direccion");

                entity.Property(e => e.IdEmp).HasColumnName("idEmp");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasColumnName("nombre");

                entity.Property(e => e.Telefono)
                    .IsRequired()
                    .HasColumnName("telefono");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}